Models/AppViewModels/RecommendBeerViewModel.cs
using System.Collections.Generic;
using BierTier.Models;

namespace BierTier.Models.AppViewModels

{
    public class RecommendBeerViewModel
    {
        public int BeerToRecommendId { get; set; }
        public List<Beer> Beers { get; set; }
        public string BeerRecommend { get; set; }
    }
}

Models/Beer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BierTier.Models
{
    public class Beer
    {
        [Key]
        public int BeerId { get; set; }

        public string Name { get; set; }
        
        public string Brewery { get; set; }

        public string Description { get; set; }

        public string Type { get; set; }

        public double ABV { get; set; }

        public int IBU { get; set; }

        public string Image { get; set; }

        public virtual ICollection<BlacklistBeer> BlacklistBeers { get; set; }
        public virtual ICollection<FavoriteBeer> FavoriteBeers { get; set; }
        public virtual ICollection<WishlistBeer> WishlistBeers { get; set; }

    }
}

Models/FavoriteBeer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BierTier.Models
{
    public class FavoriteBeer
    {
        [Key]

        public int FavoriteBeerId { get; set; }
        public int BeerId { get; set; }
        public ApplicationUser User { get; set; }
        public Beer IndivBeer { get; set; }

    }
}

Models/WishlistBeer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BierTier.Models
{
    public class WishlistBeer
    {
        [Key]
        public int WishListBeerId { get; set; }
        public int BeerId { get; set; }
        public ApplicationUser User { get; set; }
        public Beer IndivBeer { get; set; }
    }
}

Controllers/BeerController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BierTier.Data;
using BierTier.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using System.IO;
using System.Reflection;
using System.Xml.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using BierTier.Models.AppViewModels;

namespace BierTier.Controllers
{
    public class BeerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public BeerController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;    
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
        
        // GET: Beer
        public async Task<IActionResult> Index()
        {
            return View(await _context.Beer.ToListAsync());
        }

        // GET: Beer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _context.Beer
                .SingleOrDefaultAsync(m => m.BeerId == id);
            if (beer == null)
            {
                return NotFound();
            }

            return View(beer);
        }


        // GET: Beer/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Beer/Create
        // Add beer to Favorites or Wishlist

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveBeer(FavOrWishBeerViewModel viewModel)
        {
            var id = await GetCurrentUserAsync();

            if (viewModel.BeerChoice == "Add to Favorites")
            {
                FavoriteBeer beerToAdd = new FavoriteBeer(){
                    BeerId = viewModel.BeerToSaveId,
                    User = id
                };
                    _context.Add(beerToAdd);
                    await _context.SaveChangesAsync();

            return RedirectToAction ("FavoriteBeer");
            
            }
        
            else if (viewModel.BeerChoice == "Add to Wishlist")
            {
                WishlistBeer beerToAdd = new WishlistBeer(){
                    BeerId = viewModel.BeerToSaveId,
                    User = id
                };
                    _context.Add(beerToAdd);
                    await _context.SaveChangesAsync();

            return RedirectToAction ("WishlistBeer");
            }
            return View ("Index");
        }

         public async Task<IActionResult> FavoriteBeer()
        {
            var beers = await _context.FavoriteBeer.Include("IndivBeer").ToListAsync();
            return View (beers);
        }

        public async Task<IActionResult> WishlistBeer()
        {
            var wishbeers = await _context.WishlistBeer.Include("IndivBeer").ToListAsync();
            return View (wishbeers);
        }

        // GET: Beer/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _context.Beer.SingleOrDefaultAsync(m => m.BeerId == id);
            if (beer == null)
            {
                return NotFound();
            }
            return View(beer);
        }

        // POST: Beer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BeerId,Name,Brewery,Description,Type,ABV,IBU,Image")] Beer beer)
        {
            if (id != beer.BeerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(beer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BeerExists(beer.BeerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(beer);
        }

        // GET: Beer/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _context.Beer
                .SingleOrDefaultAsync(m => m.BeerId == id);
            if (beer == null)
            {
                return NotFound();
            }

            return View(beer);
        }

        // POST: Beer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var beer = await _context.Beer.SingleOrDefaultAsync(m => m.BeerId == id);
            _context.Beer.Remove(beer);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // POST: Beer/DeleteFavorite/5
        [HttpPost, ActionName("DeleteFavorite")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteFavoriteConfirmed(int id)
        {
            var beer = await _context.FavoriteBeer.SingleOrDefaultAsync(m => m.FavoriteBeerId == id);
            _context.FavoriteBeer.Remove(beer);
            await _context.SaveChangesAsync();
            return RedirectToAction("FavoriteBeer");
        }

        // POST: Beer/DeleteWishlist/5
        [HttpPost, ActionName("DeleteWishlist")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteWishlistConfirmed(int id)
        {
            var beer = await _context.WishlistBeer.SingleOrDefaultAsync(m => m.WishListBeerId == id);
            _context.WishlistBeer.Remove(beer);
            await _context.SaveChangesAsync();
            return RedirectToAction("WishlistBeer");
        }

        private bool BeerExists(int id)
        {
            return _context.Beer.Any(e => e.BeerId == id);
        }

        // Beer Search Functionality
        [ActionName("Search")]
        public async Task<IActionResult> SearchIndex(string searchString)
        {
            FavOrWishBeerViewModel viewModel = new FavOrWishBeerViewModel();

            viewModel.Beers = (from b in _context.Beer
                           select b).ToList();

            var id = await GetCurrentUserAsync();

    
            if (!String.IsNullOrEmpty(searchString))
                {
                    viewModel.Beers = viewModel.Beers.Where(b => b.Name.ToLower().Contains(searchString.ToLower())
                                        || b.Brewery.ToLower().Contains(searchString.ToLower())
                                        || b.Type.ToLower().Contains(searchString.ToLower())).ToList();
                }

            return View(viewModel);
        }

        // Beer Recommendations Functionality

        [ActionName("RecommendBeer")]
        public async Task<IActionResult> RecommendBeer(string recommendString)
        {
            RecommendBeerViewModel viewModel = new RecommendBeerViewModel();
            
            var id = await GetCurrentUserAsync();

            viewModel.Beers = _context.Beer.Where(b => b.Type.Contains(recommendString)).ToList();

            return View(viewModel);
        }
    }
}

Controllers/FavoriteBeerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BierTier.Data;
using BierTier.Models;
using Microsoft.AspNetCore.Identity;

namespace BierTier.Controllers
{
    public class FavoriteBeerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public FavoriteBeerController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;    
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
        
        // GET: FavoriteBeer
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.FavoriteBeer.Include(f => f.IndivBeer);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: FavoriteBeer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var favoriteBeer = await _context.FavoriteBeer
                .Include(f => f.IndivBeer)
                .SingleOrDefaultAsync(m => m.FavoriteBeerId == id);
            if (favoriteBeer == null)
            {
                return NotFound();
            }

            return View(favoriteBeer);
        }

        // GET: FavoriteBeer/Create
        public IActionResult Create()
        {
            ViewData["BeerId"] = new SelectList(_context.Beer, "BeerId", "BeerId");
            return View();
        }

        // POST: FavoriteBeer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FavoriteBeerId,BeerId")] FavoriteBeer favoriteBeer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(favoriteBeer);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["BeerId"] = new SelectList(_context.Beer, "BeerId", "BeerId", favoriteBeer.BeerId);
            return View(favoriteBeer);
        }

        // GET: FavoriteBeer/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var favoriteBeer = await _context.FavoriteBeer.SingleOrDefaultAsync(m => m.FavoriteBeerId == id);
            if (favoriteBeer == null)
            {
                return NotFound();
            }
            ViewData["BeerId"] = new SelectList(_context.Beer, "BeerId", "BeerId", favoriteBeer.BeerId);
            return View(favoriteBeer);
        }

        // POST: FavoriteBeer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FavoriteBeerId,BeerId")] FavoriteBeer favoriteBeer)
        {
            if (id != favoriteBeer.FavoriteBeerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(favoriteBeer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FavoriteBeerExists(favoriteBeer.FavoriteBeerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["BeerId"] = new SelectList(_context.Beer, "BeerId", "BeerId", favoriteBeer.BeerId);
            return View(favoriteBeer);
        }

        // GET: FavoriteBeer/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var favoriteBeer = await _context.FavoriteBeer
                .Include(f => f.IndivBeer)
                .SingleOrDefaultAsync(m => m.FavoriteBeerId == id);
            if (favoriteBeer == null)
            {
                return NotFound();
            }

            return View(favoriteBeer);
        }

        // POST: FavoriteBeer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var favoriteBeer = await _context.FavoriteBeer.SingleOrDefaultAsync(m => m.FavoriteBeerId == id);
            _context.FavoriteBeer.Remove(favoriteBeer);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool FavoriteBeerExists(int id)
        {
            return _context.FavoriteBeer.Any(e => e.FavoriteBeerId == id);
        }
    }
}

Views/Beer/Create.cshtml
@model BierTier.Models.Beer

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Beer</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Brewery" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Brewery" class="form-control" />
                <span asp-validation-for="Brewery" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Type" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ABV" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ABV" class="form-control" />
                <span asp-validation-for="ABV" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="IBU" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IBU" class="form-control" />
                <span asp-validation-for="IBU" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Image" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Views/Beer/Delete.cshtml
@model BierTier.Models.Beer

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Beer</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="BeerId" />
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Brewery)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Brewery)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ABV)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ABV)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IBU)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IBU)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

Views/Beer/DeleteFavorite.cshtml
@model BierTier.Models.FavoriteBeer

@{
    ViewData["Title"] = "DeleteFavorite";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="FavoriteBeerId" />
        <dt>
            @Html.DisplayNameFor(model => model.IndivBeer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IndivBeer.BeerId)
        </dd>
    </dl>
    
    <form asp-action="DeleteFavorite">
        <div class="form-actions no-color">
            <input type="submit" value="DeleteFavorite" class="btn btn-default btn-sm btn-danger" />
            <a asp-action="FavoriteBeer">Back to List</a>
        </div>
    </form>
</div>

Views/Beer/Details.cshtml
@model BierTier.Models.Beer

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div class>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Brewery)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Brewery)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ABV)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ABV)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IBU)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IBU)
        </dd>
        <dd>
            <img src="@Html.DisplayFor(model => model.Image)" img class="img-responsive" height=250 width=200/>
            <!-- @Html.DisplayFor(model => model.Image) -->
        </dd>
    </dl>
</div>
<div>
    <!-- <a asp-action="Edit" asp-route-id="@Model.BeerId">Edit</a> | -->
    <!-- <a asp-action="Index">Back to List</a> -->
</div>

Views/Beer/Edit.cshtml
@model BierTier.Models.Beer

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Beer</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="BeerId" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Brewery" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Brewery" class="form-control" />
                <span asp-validation-for="Brewery" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Type" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ABV" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ABV" class="form-control" />
                <span asp-validation-for="ABV" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="IBU" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IBU" class="form-control" />
                <span asp-validation-for="IBU" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Image" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Views/Beer/FavoriteBeer.cshtml
@model IEnumerable<BierTier.Models.FavoriteBeer>

@{
    ViewData["Title"] = "FavoriteBeer";
}

<h2>My Favorite Beers</h2>

<table class="table">
    <thead>
        <tr>
            <th>Beer
            </th>
            <th>Brewery</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IndivBeer.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IndivBeer.Brewery)
            </td>
            <td>
                <img src="@Html.DisplayFor(modelItem => item.IndivBeer.Image)" img class="img-responsive" height=150 width=100/>
            </td>
            <td>
                <p><a asp-action="Details" asp-route-id="@item.BeerId" class="btn btn-primary btn-md resultsbutton">Details</a></p>
                <form asp-action="DeleteFavorite">
                    <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default btn-sm btn-danger" />
                    <input type="hidden" name="Id" value="@item.FavoriteBeerId" />
                    </div>
                </form>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Beer/RecommendBeer.cshtml
@model BierTier.Models.AppViewModels.RecommendBeerViewModel

@{
    ViewData["Title"] = "RecommendBeer";
}

<!-- Recommend Logic in BeerController.cs -->

<h2>Similar Beers</h2>

@if(Model.Beers.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th></th>
                    <th>
                        Beer
                    </th>
                    <th>
                        Brewery
                    </th>
                    <th>
                        Type
                    </th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model.Beers) 
        {
        <tr>
            <td>
                <img src="@Html.DisplayFor(modelItem => item.Image)" img class="img-responsive" height=150 width=100/>
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.BeerId" class="btn btn-info btn-md">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brewery)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <!-- <td>
                <p><a asp-action="Details" asp-route-id="@item.BeerId" class="btn btn-primary btn-md resultsbutton">Details</a></p>
            </td> -->
            <td>
            <form asp-controller="Beer" asp-action="SaveBeer" method="post">
                <input type="hidden" asp-for="@Model.BeerToRecommendId" value="@item.BeerId" />
                <input type="submit"  asp-for="@Model.BeerRecommend" value="Add to Favorites" class="btn btn-primary addbuttons">
                <input type="submit"  asp-for="@Model.BeerRecommend" value="Add to Wishlist" class="btn btn-primary addbuttons">
            </form>
            </td>
        </tr> 
        }
    </tbody>
</table>
}

else
{
    <h4>No similar beers found.</h4>
}

Views/Beer/Search.cshtml
@model BierTier.Models.AppViewModels.FavOrWishBeerViewModel

@{
    ViewData["Title"] = "Search";
}
<!-- Search logic in BeerController.cs -->
<h3 class="findtext">Find a beer.</h3>
<br>

@using (Html.BeginForm())
{
    @Html.TextBox("SearchString")
    <div class="input-group input-group-lg text-center">
        <br>
        <input asp-area="" asp-controller="Beer" asp-action="Search" type="submit" class="form-control btn btn-primary searchbutton" value="Search" />
    </div>
}
<br>

@if(Model.Beers.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th></th>
                    <th>
                        Beer
                    </th>
                    <th>
                        Brewery
                    </th>
                    <th>
                        Type
                    </th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model.Beers) 
        {
        <tr>
            <td>
                <img src="@Html.DisplayFor(modelItem => item.Image)" img class="img-responsive" height=150 width=100/>
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.BeerId" class="btn btn-info btn-sm addbuttons">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brewery)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <!-- <td>
                <p><a asp-action="Details" asp-route-id="@item.BeerId" class="btn btn-primary btn-sm addbuttons">Details</a></p>
            </td> -->
            <td>
            <form asp-controller="Beer" asp-action="SaveBeer" method="post" class="btn-group">
                <input type="hidden" asp-for="@Model.BeerToSaveId" value="@item.BeerId" />
                <input type="submit"  asp-for="@Model.BeerChoice" value="Add to Favorites" class="btn btn-primary btn-sm addbuttons">
                <input type="submit"  asp-for="@Model.BeerChoice" value="Add to Wishlist" class="btn btn-primary btn-sm addbuttons">
            </form>
            <form asp-controller="Beer" asp-action="RecommendBeer" method="post">
                <input type="hidden" name="recommendString" value="@item.Type" />
                <input type="submit" value="See Similar Beers!" class="btn btn-primary similarbutton">
            </form>
            </td>
        </tr> 
        }
    </tbody>
</table>
}

else
{
    <h4>No matching beers found.</h4>
}